name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - stage  # Ejecutar este workflow solo en la rama 'stage'

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "ap-southeast-2"
      AWS_ACCOUNT_ID: "969288724771"
      ECR_REPOSITORY: "backend_python_stage"
      IMAGE_TAG: "latest"  # Puedes cambiar la etiqueta de la imagen según tus necesidades

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
